apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  appUrl: "http://my-app-service"
  timeout: "30"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    envFrom:
    - configMapRef:
        name: app-properties
    args:
    - env
