apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  app.key: |
    YXBpVmVyc2lvbjogdjEKa2luZDogQ29uZmlnTWFwCm1ldGFkYXRhOgogIG5hbWU6IGFwcC1wcm9w
    ZXJ0aWVzCmRhdGE6CiAgYXBwVXJsOiAiaHR0cDovL215LWFwcC1zZXJ2aWNlIgogIHRpbWVvdXQ6
    ICIzMCIKLS0tCmFwaVZlcnNpb246IHYxCmtpbmQ6IFBvZAptZXRhZGF0YToKICBuYW1lOiBteS1w
    b2QKc3BlYzoKICByZXN0YXJ0UG9saWN5OiBOZXZlcgogIGNvbnRhaW5lcnM6CiAgLSBuYW1lOiB1
    YnVudHUKICAgIGltYWdlOiB1YnVudHUKICAgIHJlc291cmNlczoKICAgICAgbGltaXRzOgogICAg
    ICAgIG1lbW9yeTogIjUxMk1pIgogICAgICAgIGNwdTogIjUwMG0iCiAgICAgIHJlcXVlc3RzOgog
    ICAgICAgIG1lbW9yeTogIjY0TWkiCiAgICAgICAgY3B1OiAiMjUwbSIKICAgIGVudjoKICAgIC0g
    bmFtZTogInJlcXVlc3QudGltZW91dCIKICAgICAgdmFsdWVGcm9tOgogICAgICAgIGNvbmZpZ01h
    cEtleVJlZjoKICAgICAgICAgIG5hbWU6IGFwcC1wcm9wZXJ0aWVzCiAgICAgICAgICBrZXk6IHRp
    bWVvdXQKICAgIC0gbmFtZTogImFwcGxpY2F0aW9uLnVybCIKICAgICAgdmFsdWVGcm9tOgogICAg
    ICAgIGNvbmZpZ01hcEtleVJlZjoKICAgICAgICAgIG5hbWU6IGFwcC1wcm9wZXJ0aWVzCiAgICAg
    ICAgICBrZXk6IGFwcFVybAogICAgYXJnczoKICAgIC0gZW52ICAgICAgICAgIAo=
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    volumeMounts:
    - name: secret-volume
      mountPath: /usr/share/props  
    args:
    - sleep
    - "3600"
  volumes:
  - name: secret-volume
    secret:
      secretName: app-secret   