apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    owner: tarso
    objective: test
  annotations:
    description: Openshift Course
spec:
  containers:
  - name: busybox
    image:                  image-registry.openshift-image-registry.svc:5000/tarsodemo/busybox-v1.37.0-glibc:1.37.0-glibc # OK
    # image: default-route-openshift-image-registry.apps.ocp4.celepar.parana/tarsodemo/busybox-v1.37.0-glibc:1.37.0-glibc # NOK
    # image:                                            imagestream.image.openshift.io/busybox-v1.37.0-glibc:1.37.0-glibc # NOK
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "125m"
      limits:
        memory: "64Mi"
        cpu: "250m"
    env:
    - name: POD_OWNER
      value: "Tarso Queiroz"
    - name: POD_DESCRIPTION
      value: "Openshift Course"
