apiVersion: v1
kind: Pod
metadata:
  name: pod-assignment
spec:
  restartPolicy: OnFailure
  containers:
  - name: assignment
    image: vinsdocker/k8s-pod-assignment
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    env:
    - name: NUMBER
      value: "5"
    args:
    - "MY_ARG"
