kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

name: gwfabric

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080 # Porta que o NodePort usar√° internamente
        hostPort: 80         # Porta no seu computador
        protocol: TCP
      - containerPort: 30443
        hostPort: 443
        protocol: TCP
      - containerPort: 31080
        hostPort: 8080
        protocol: TCP
      - containerPort: 31443
        hostPort: 8443
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker

networking:
  disableDefaultCNI: true
  apiServerPort: 6443
  apiServerAddress: "0.0.0.0"
