apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  selector:
    matchLabels:
      team: team-a
  replicas: 3
  template:
    metadata:
      labels:
        team: team-a
    spec:
      containers:
      - name: nginx
        image: nginx