apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache1
  namespace: tarsodemo
spec:
  selector:
    matchLabels:
      app: example-apache
  replicas: 3
  template:
    metadata:
      labels:
        app: example-apache
    spec:
      containers:
        - name: apache
          image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 80