apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-secrets
spec:
  selector:
    matchLabels:
      app: secrets
  replicas: 2
  template:
    metadata:
      labels:
        app: secrets
    spec:
      containers:
        - name: secrets
          # image: gcr.io/google-samples/node-hello:1.0
          image: ppc64le/busybox:stable-musl
          command: ["sleep", "3600"]
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          envFrom:
          - secretRef:
              name: secret-cm
