apiVersion: v1
kind: Pod
metadata:
  name: nginx-openshift
  labels:
    zone: prod
    version: v1
  annotations:
    description: Apasoft-Training Openshift Course
spec:
  containers:
   - name: nginx   
     image: nginx