apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment
  annotations:
    kubernetes.io/change-cause: "k8s-deploy-assignment v1"
spec:
  selector:
    matchLabels:
      app: assignment
  replicas: 1
  template:
    metadata:
      labels:
        app: assignment
    spec:
      containers:
      - name: assignment
        image: vinsdocker/k8s-deploy-assignment
        ports:
        - containerPort: 8080
          name: "app-port"
        env:
        - name: "spring.redis.host"
          value: "10.244.1.65" 
          # Not the best solution. Just temporary
        - name: "spring.redis.port"
          value: "6379"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
          requests:
            memory: "64Mi"
            cpu: "250m"
